In [3]:
import torch

data = [[1, 2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [14]:
tensor = x_data
tensor[:,1] = 0
print(tensor)

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

print(y1)
print(y2)

tensor([[1, 0],
        [3, 0]])
tensor([[1, 3],
        [3, 9]])
tensor([[1, 3],
        [3, 9]])
